parse_config:
  zmk_remove_keycode_prefix: []
  raw_binding_map:
    "&bootloader": "BOOT"
    "&sys_reset": "RST"
    "&bt BT_CLR": "BT CLR"
    "&bt BT_SEL 0": "BT 0"
    "&bt BT_SEL 1": "BT 1"
    "&bt BT_SEL 2": "BT 2"
    "&bt BT_SEL 3": "BT 3"
    "&bt BT_SEL 4": "BT 4"
    "&rgb_ug RGB_TOG": "RGB"
    "&kp LS(DEL)": "Cut"
    "&kp LC(INS)": "Copy"
    "&kp LS(INS)": "Paste"
    "&kp K_UNDO": "Undo"
    "&kp K_AGAIN": "Again"

draw_config:
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  key_h: 60.0
  n_columns: 3  # 3-column layout for compact display
